### ISSUE TITLE
In page getting_started/installing-gauge.rst not find plugin for java - IntelliJ IDEA

### ISSUE THREAD

**Issue by AntonDzyk** [getgauge/docs.gauge.org#326]
I found plugin for Intellij IDEA

https://github.com/JetBrains/intellij-plugins/tree/master/gauge

but, I don't find its on page getting_started/installing-gauge.rst.

Can I make PR for add this plugin in `getting_started/installing-gauge.rst` ?

**Comment by zabil** [comment]
@AntonDzyk thanks for offering help.

The sections in the document referring to IntellIj was [removed](https://github.com/getgauge/docs.gauge.org/commit/63bd61fdf099e6b7e91ef9befe293211c67a1347) after transferring the ownership of the plugin over to IntelliJ. It's best to update the documentation at https://plugins.jetbrains.com/plugin/7535-gauge so that it does not go out of date.
